
import React, { useState, useCallback } from 'react';
import { InputMode, AnalysisState, SunoPrompt } from './types';
import { analyzeAudioFile, analyzeMusicUrl } from './services/geminiService';
import { FileUp, Link, Loader2, Music, Copy, Download, RefreshCcw, Zap, Search, Mic } from 'lucide-react';

export default function App() {
  const [mode, setMode] = useState<InputMode>('file');
  const [file, setFile] = useState<File | null>(null);
  const [url, setUrl] = useState('');
  const [context, setContext] = useState('');
  const [state, setState] = useState<AnalysisState>({
    loading: false,
    error: null,
    result: null,
    rawMarkdown: ''
  });

  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => resolve(reader.result?.toString().split(',')[1] || '');
      reader.onerror = (error) => reject(error);
    });
  };

  const handleProcess = async () => {
    setState(prev => ({ ...prev, loading: true, error: null }));
    try {
      let result: SunoPrompt;
      if (mode === 'file' && file) {
        const base64 = await fileToBase64(file);
        result = await analyzeAudioFile(base64, file.type, context);
      } else if (mode === 'url' && url) {
        result = await analyzeMusicUrl(url, context);
      } else {
        throw new Error("Please provide input data.");
      }

      const markdown = `
# Suno AI Style Prompt Reconstruction

**Genre:** ${result.genre}
**Vocal Style:** ${result.vocalStyle}
**Instruments:** ${result.instruments}
**Production Style:** ${result.productionStyle}
**Mood:** ${result.mood}
**Tempo:** ${result.tempo}

---
*Generated by SunoReverse v1.0 - dim-gggl*
      `.trim();

      setState({ loading: false, result, error: null, rawMarkdown: markdown });
    } catch (err: any) {
      setState(prev => ({ ...prev, loading: false, error: err.message || "An unexpected error occurred." }));
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(state.rawMarkdown);
  };

  const downloadMarkdown = () => {
    const blob = new Blob([state.rawMarkdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `suno-prompt-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen relative overflow-hidden flex flex-col items-center p-4 md:p-8">
      <div className="scanline-effect"></div>
      
      {/* Header */}
      <header className="w-full max-w-4xl flex flex-col md:flex-row justify-between items-center mb-12 relative z-10">
        <div className="flex items-center gap-3 mb-4 md:mb-0">
          <div className="w-12 h-12 bg-[#ccff00] rounded-sm flex items-center justify-center rotate-3 hover:rotate-0 transition-transform cursor-pointer">
            <Music className="text-black" />
          </div>
          <h1 className="text-4xl font-black italic tracking-tighter">
            SUNO<span className="text-[#ccff00]">REVERSE</span>
          </h1>
        </div>
        <div className="flex gap-4">
          <button 
            onClick={() => setMode('file')}
            className={`px-4 py-2 border-b-2 transition-all ${mode === 'file' ? 'border-[#ccff00] text-[#ccff00]' : 'border-transparent text-gray-500'}`}
          >
            FILE UPLOAD
          </button>
          <button 
            onClick={() => setMode('url')}
            className={`px-4 py-2 border-b-2 transition-all ${mode === 'url' ? 'border-[#ccff00] text-[#ccff00]' : 'border-transparent text-gray-500'}`}
          >
            MAGIC LINK
          </button>
        </div>
      </header>

      {/* Main UI */}
      <main className="w-full max-w-4xl grid grid-cols-1 lg:grid-cols-12 gap-8 relative z-10">
        
        {/* Left: Input Panel */}
        <section className="lg:col-span-5 flex flex-col gap-6">
          <div className="glass p-8 rounded-none border-l-4 border-l-[#ccff00] transition-all hover:bg-black/80">
            <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
              <Zap className="w-5 h-5 text-[#ccff00]" /> INPUT_SOURCE
            </h2>
            
            {mode === 'file' ? (
              <div className="space-y-4">
                <label className="group block w-full border-2 border-dashed border-gray-700 hover:border-[#ccff00] p-10 cursor-pointer transition-all text-center relative overflow-hidden">
                  <input 
                    type="file" 
                    className="hidden" 
                    accept="audio/*" 
                    onChange={(e) => setFile(e.target.files?.[0] || null)}
                  />
                  <FileUp className="w-12 h-12 mx-auto mb-4 text-gray-500 group-hover:text-[#ccff00] transition-colors relative z-10" />
                  <p className="text-sm text-gray-400 relative z-10 break-all">
                    {file ? file.name : "DROP AUDIO FILE OR CLICK TO BROWSE"}
                  </p>
                  {file && <div className="absolute inset-0 bg-[#ccff00]/5 z-0"></div>}
                </label>
                <p className="text-[10px] text-gray-600 uppercase tracking-widest">Supports: MP3, WAV, M4A</p>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="relative">
                  <Link className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 w-5 h-5" />
                  <input 
                    type="text" 
                    placeholder="https://youtube.com/watch?v=..." 
                    className="w-full bg-black/50 border border-gray-700 p-4 pl-12 focus:border-[#ccff00] outline-none transition-all text-sm font-mono text-[#ccff00]"
                    value={url}
                    onChange={(e) => setUrl(e.target.value)}
                  />
                </div>
                <p className="text-[10px] text-gray-600 uppercase tracking-widest">YouTube, Spotify, Soundcloud</p>
              </div>
            )}

            {/* Context Input */}
            <div className="space-y-2 pt-4 border-t border-gray-800">
               <label className="text-[10px] uppercase tracking-widest text-[#ccff00] flex items-center gap-2">
                 <Search className="w-3 h-3" /> Search Context (Optional)
               </label>
               <input 
                 type="text"
                 placeholder={mode === 'file' ? "e.g. Artist - Track Name" : "e.g. Correct Title if URL is ambiguous"}
                 className="w-full bg-black/50 border border-gray-700 p-3 focus:border-[#ccff00] outline-none transition-all text-sm font-mono text-gray-300 placeholder-gray-700"
                 value={context}
                 onChange={(e) => setContext(e.target.value)}
               />
               <p className="text-[10px] text-gray-600">
                 Helps the AI find reviews & metadata via Google Search.
               </p>
            </div>

            <button 
              onClick={handleProcess}
              disabled={state.loading || (mode === 'file' ? !file : !url)}
              className="w-full mt-4 bg-[#ccff00] text-black font-bold py-4 hover:bg-white active:scale-95 transition-all disabled:opacity-50 disabled:grayscale uppercase tracking-tighter text-lg relative overflow-hidden"
            >
              {state.loading ? (
                <span className="flex items-center justify-center gap-2">
                  <Loader2 className="animate-spin" /> 
                  <span className="animate-pulse">THINKING...</span>
                </span>
              ) : "DECONSTRUCT"}
            </button>
          </div>

          {state.error && (
            <div className="p-4 bg-red-900/20 border border-red-500 text-red-400 text-xs uppercase animate-pulse font-mono">
              ERROR_LOG: {state.error}
            </div>
          )}
        </section>

        {/* Right: Output Panel */}
        <section className="lg:col-span-7">
          <div className="glass h-full min-h-[500px] flex flex-col relative overflow-hidden group">
            <div className="absolute top-0 right-0 p-4 flex gap-2 z-20">
              {state.result && (
                <>
                  <button onClick={copyToClipboard} className="p-2 bg-gray-800 hover:bg-[#ccff00] hover:text-black transition-colors rounded-sm" title="Copy Markdown">
                    <Copy className="w-4 h-4" />
                  </button>
                  <button onClick={downloadMarkdown} className="p-2 bg-gray-800 hover:bg-[#ccff00] hover:text-black transition-colors rounded-sm" title="Download .md">
                    <Download className="w-4 h-4" />
                  </button>
                </>
              )}
            </div>

            <div className="flex-1 p-8 font-mono text-sm relative z-10">
              {!state.result && !state.loading && (
                <div className="h-full flex flex-col items-center justify-center text-gray-600 text-center space-y-4 opacity-50">
                  <div className="relative">
                    <RefreshCcw className="w-16 h-16 animate-spin-slow text-gray-700" />
                    <Zap className="w-6 h-6 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-gray-500" />
                  </div>
                  <p className="uppercase tracking-[0.2em]">Awaiting Input Signal</p>
                </div>
              )}

              {state.loading && (
                <div className="h-full flex flex-col items-center justify-center space-y-6">
                  <div className="w-full max-w-xs space-y-2">
                    <div className="flex justify-between text-[10px] text-[#ccff00] uppercase tracking-widest">
                       <span>Analyzing</span>
                       <span className="animate-pulse">...</span>
                    </div>
                    <div className="h-1 bg-gray-800 w-full overflow-hidden">
                       <div className="h-full bg-[#ccff00] animate-indeterminate-bar"></div>
                    </div>
                    <div className="text-xs text-gray-500 font-mono text-center pt-2">
                      Accessing Gemini 3.1 Pro Neural Network...<br/>
                      Running Web Search...<br/>
                      Deconstructing Audio Waveforms...
                    </div>
                  </div>
                </div>
              )}

              {state.result && (
                <div className="space-y-6 overflow-y-auto max-h-[60vh] pr-4 scrollbar-thin">
                  <div className="animate-in fade-in slide-in-from-bottom-2 duration-500">
                    <label className="text-[#ccff00] text-[10px] block mb-1 uppercase tracking-widest">/ Genre</label>
                    <p className="text-white text-lg font-bold">{state.result.genre}</p>
                  </div>
                  <div className="animate-in fade-in slide-in-from-bottom-2 duration-500 delay-100">
                    <label className="text-[#ccff00] text-[10px] block mb-1 uppercase tracking-widest">/ Vocal_Style</label>
                    <p className="text-gray-300">{state.result.vocalStyle}</p>
                  </div>
                  <div className="animate-in fade-in slide-in-from-bottom-2 duration-500 delay-200">
                    <label className="text-[#ccff00] text-[10px] block mb-1 uppercase tracking-widest">/ Instrumentation</label>
                    <p className="text-gray-300">{state.result.instruments}</p>
                  </div>
                  <div className="animate-in fade-in slide-in-from-bottom-2 duration-500 delay-300">
                    <label className="text-[#ccff00] text-[10px] block mb-1 uppercase tracking-widest">/ Production</label>
                    <p className="text-gray-300 italic border-l-2 border-gray-700 pl-3">{state.result.productionStyle}</p>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="animate-in fade-in slide-in-from-bottom-2 duration-500 delay-400">
                      <label className="text-[#ccff00] text-[10px] block mb-1 uppercase tracking-widest">/ Mood</label>
                      <p className="text-gray-300">{state.result.mood}</p>
                    </div>
                    <div className="animate-in fade-in slide-in-from-bottom-2 duration-500 delay-500">
                      <label className="text-[#ccff00] text-[10px] block mb-1 uppercase tracking-widest">/ Tempo</label>
                      <p className="text-gray-300">{state.result.tempo}</p>
                    </div>
                  </div>
                </div>
              )}
            </div>
            
            {/* Visualizer Footer Deco */}
            <div className="h-1 bg-gray-900 flex gap-px p-px mt-auto">
               {Array.from({length: 60}).map((_, i) => (
                 <div key={i} className={`flex-1 transition-all duration-100 ${state.loading ? 'bg-[#ccff00]' : 'bg-gray-800'}`}
                      style={{ 
                        height: state.loading ? `${Math.random() * 100}%` : `${20 + Math.random() * 30}%`,
                        opacity: state.loading ? 0.8 : 0.3
                      }}></div>
               ))}
            </div>
          </div>
        </section>
      </main>

      {/* Decorative Elements */}
      <footer className="w-full max-w-4xl mt-auto pt-12 pb-4 flex justify-between items-end border-t border-gray-900 text-[10px] text-gray-700 font-mono tracking-widest relative z-10">
        <div>
          CORE_ENGINE: GEMINI_3.1_PRO_PREVIEW<br/>
          MODULE: THINKING_MODE_ENABLED
        </div>
        <div className="text-right">
          (C) 2025 DIM-GGGL<br/>
          ALL_RIGHTS_REVERSED
        </div>
      </footer>
      
      <style>{`
        @keyframes indeterminate-bar {
          0% { transform: translateX(-100%); }
          50% { transform: translateX(50%); }
          100% { transform: translateX(200%); }
        }
        .animate-indeterminate-bar {
          animation: indeterminate-bar 1.5s infinite linear;
        }
      `}</style>
    </div>
  );
}
